"""Conversion job tests (Specification §7-8): profile CRUD, production
replace, test-mode preserve, invalid-output safety, variant sweep,
skip-processed, and directory recursion excluding test artifacts.

Runs real ffmpeg/ffprobe against tiny synthetic videos generated by
make_video() (skipped automatically if ffmpeg/ffprobe aren't on PATH).
"""

from __future__ import annotations

import shutil

import pytest
from sqlalchemy import text

from app import conversion, conversion_profiles
from app.jobs import convert, service
from app.scan import scan_source

from .conftest import make_video

pytestmark = pytest.mark.skipif(
    shutil.which("ffmpeg") is None or shutil.which("ffprobe") is None,
    reason="ffmpeg/ffprobe not on PATH",
)


def _make_profile(engine, **overrides) -> dict:
    data = {
        "name": "Test Profile",
        "video_codec": "h265",
        "container": "mp4",
        "crf": 30,
        "drop_audio": True,
        "max_dimension": None,
    }
    data.update(overrides)
    return conversion_profiles.create_profile(engine, data)


def _run_job(engine, scope_type: str, scope_ref: str | None, parameters: dict) -> dict:
    job = service.create_job(engine, "convert", scope_type, scope_ref, parameters)
    service.start_job(engine, job["id"])
    status, message = convert.run_convert_job(engine, job)
    service.finish_job(engine, job["id"], status, message)
    return service.get_job(engine, job["id"])


def _file_row(engine, relative_path: str):
    with engine.connect() as conn:
        return conn.execute(
            text("SELECT * FROM files WHERE relative_path = :rel"), {"rel": relative_path}
        ).fetchone()


# --- probe_media --------------------------------------------------------------


def test_probe_media_returns_none_instead_of_raising_on_null_stdout(tmp_path, monkeypatch):
    """Regression test: a 0 exit code with `stdout=None` (observed
    intermittently on Windows across many back-to-back ffprobe calls) used to
    raise an uncaught `TypeError` out of `json.loads(None)`, surfacing as a
    cryptic job-item failure message instead of the normal "not probeable"
    path."""
    fake_result = type("FakeResult", (), {"returncode": 0, "stdout": None})()
    monkeypatch.setattr(conversion.subprocess, "run", lambda *a, **k: fake_result)

    assert conversion.probe_media(tmp_path / "clip.mp4") is None


def test_probe_media_handles_non_ascii_path(tmp_path):
    """Regression test: `ffprobe`'s JSON output is UTF-8, but `subprocess.run`
    without an explicit `encoding` decodes with the OS console codepage (e.g.
    cp1252 on many Windows setups). For a path containing non-Latin-1
    characters (e.g. Cyrillic folder/file names), that mismatch used to raise
    a `UnicodeDecodeError` inside subprocess's stdout reader thread, silently
    truncating `result.stdout` and making a perfectly valid video look "not
    probeable"."""
    video_path = tmp_path / "Я умею любить" / "клип.mp4"
    make_video(video_path, duration=1.0, size="320x240")

    info = conversion.probe_media(video_path)
    assert info is not None
    assert info["has_video_stream"] is True
    assert info["duration"] is not None


# --- profile CRUD ------------------------------------------------------------


def test_profile_crud_and_default_exclusivity(engine, source):
    p1 = conversion_profiles.create_profile(engine, {"name": "A", "is_default": True})
    p2 = conversion_profiles.create_profile(engine, {"name": "B", "is_default": True})

    profiles = {p["id"]: p for p in conversion_profiles.list_profiles(engine)}
    assert profiles[p1["id"]]["is_default"] is False
    assert profiles[p2["id"]]["is_default"] is True

    updated = conversion_profiles.update_profile(engine, p1["id"], {**p1, "crf": 24})
    assert updated["crf"] == 24

    assert conversion_profiles.delete_profile(engine, p1["id"]) is True
    assert conversion_profiles.get_profile(engine, p1["id"]) is None


# --- production mode ----------------------------------------------------------


def test_production_mode_replaces_file(engine, source):
    make_video(source["root"] / "clips" / "movie.avi")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/movie.avi")

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "production"},
    )

    assert job["status"] == "completed"
    assert not (source["root"] / "clips" / "movie.avi").exists()
    converted_path = source["root"] / "clips" / "movie.mp4"
    assert converted_path.exists()

    info = conversion.probe_media(converted_path)
    assert info["video_codec_name"] == "hevc"

    row = _file_row(engine, "clips/movie.mp4")
    assert row is not None
    assert row.converted_at is not None
    assert row.last_conversion_profile_id == profile["id"]
    assert row.id == file_row.id  # same logical file, just renamed/re-encoded in place


def test_invalid_conversion_never_deletes_original(engine, source, monkeypatch):
    make_video(source["root"] / "clips" / "movie.mp4")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/movie.mp4")

    monkeypatch.setattr(conversion, "validate_converted_output", lambda *a, **k: (False, "forced invalid"))

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "production"},
    )

    assert job["status"] == "failed"
    assert (source["root"] / "clips" / "movie.mp4").exists()

    items = service.get_job_items(engine, job["id"])
    assert items[0]["status"] == "failed"
    assert "Validation failed" in items[0]["message"]

    row = _file_row(engine, "clips/movie.mp4")
    assert row.converted_at is None

    leftovers = list((source["root"] / "clips").glob(".movie.convert-*"))
    assert leftovers == []


# --- test mode -----------------------------------------------------------------


def test_test_mode_preserves_original_same_extension(engine, source):
    make_video(source["root"] / "clips" / "clip.mp4")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/clip.mp4")

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "test"},
    )

    assert job["status"] == "completed"
    assert (source["root"] / "clips" / "clip.original.mp4").exists()
    assert (source["root"] / "clips" / "clip.mp4").exists()

    original_row = _file_row(engine, "clips/clip.original.mp4")
    converted_row = _file_row(engine, "clips/clip.mp4")
    assert original_row.id == file_row.id
    assert original_row.converted_at is None
    assert converted_row.id != original_row.id
    assert converted_row.converted_at is not None


def test_test_mode_preserves_original_different_extension(engine, source):
    make_video(source["root"] / "clips" / "clip.mov")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/clip.mov")

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "test"},
    )

    assert job["status"] == "completed"
    assert (source["root"] / "clips" / "clip.original.mov").exists()
    assert (source["root"] / "clips" / "clip.mp4").exists()


def test_invalid_test_mode_conversion_never_touches_original(engine, source, monkeypatch):
    make_video(source["root"] / "clips" / "clip.mp4")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/clip.mp4")

    monkeypatch.setattr(conversion, "validate_converted_output", lambda *a, **k: (False, "forced invalid"))

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "test"},
    )

    assert job["status"] == "failed"
    assert (source["root"] / "clips" / "clip.mp4").exists()
    assert not (source["root"] / "clips" / "clip.original.mp4").exists()


# --- variant comparison --------------------------------------------------------


def test_variant_sweep_never_touches_source(engine, source):
    make_video(source["root"] / "clips" / "clip.mp4")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/clip.mp4")
    original_size = (source["root"] / "clips" / "clip.mp4").stat().st_size

    variants = [{"crf": 24}, {"max_dimension": 100, "crf": 30}]
    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "test", "variants": variants},
    )

    assert job["status"] == "completed"
    assert (source["root"] / "clips" / "clip.mp4").exists()
    assert (source["root"] / "clips" / "clip.mp4").stat().st_size == original_size

    variant_files = sorted(p.name for p in (source["root"] / "clips").glob("clip.variant-*.mp4"))
    assert variant_files == ["clip.variant-crf24.mp4", "clip.variant-d100-crf30.mp4"]

    items = service.get_job_items(engine, job["id"])
    assert len(items) == 2
    assert all(item["status"] == "completed" for item in items)

    row = _file_row(engine, "clips/clip.mp4")
    assert row.converted_at is None


# --- skip-processed and directory recursion ------------------------------------


def test_directory_scope_skip_processed(engine, source):
    make_video(source["root"] / "clips" / "a.mp4")
    make_video(source["root"] / "clips" / "b.mp4")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)

    a_row = _file_row(engine, "clips/a.mp4")
    with engine.begin() as conn:
        conn.execute(
            text("UPDATE files SET converted_at = :now WHERE id = :id"),
            {"now": "2020-01-01T00:00:00+00:00", "id": a_row.id},
        )

    job = _run_job(
        engine, "directory", "clips",
        {"path": "clips", "profile_id": profile["id"], "mode": "production", "skip_processed": True},
    )

    assert job["status"] == "completed"
    items = service.get_job_items(engine, job["id"])
    statuses = sorted(item["status"] for item in items)
    assert statuses == ["completed", "skipped"]


def test_directory_recursive_conversion_excludes_test_artifacts(engine, source):
    make_video(source["root"] / "top.mp4")
    make_video(source["root"] / "sub" / "nested.mp4")
    (source["root"] / "sub" / "already.original.mp4").write_bytes(b"0")
    (source["root"] / "sub" / "already.variant-crf28.mp4").write_bytes(b"0")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)

    job = _run_job(
        engine, "source", None,
        {"path": "", "profile_id": profile["id"], "mode": "production", "skip_processed": True},
    )

    assert job["status"] == "completed"
    items = service.get_job_items(engine, job["id"])
    assert len(items) == 2  # top.mp4 + sub/nested.mp4 only; the two artifacts are excluded entirely

    assert (source["root"] / "top.mp4").exists()
    assert (source["root"] / "sub" / "nested.mp4").exists()


def test_directory_test_mode_recursive(engine, source):
    make_video(source["root"] / "top.mp4")
    make_video(source["root"] / "sub" / "nested.mp4")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)

    job = _run_job(
        engine, "source", None,
        {"path": "", "profile_id": profile["id"], "mode": "test", "skip_processed": True},
    )

    assert job["status"] == "completed"
    assert (source["root"] / "top.original.mp4").exists()
    assert (source["root"] / "top.mp4").exists()
    assert (source["root"] / "sub" / "nested.original.mp4").exists()
    assert (source["root"] / "sub" / "nested.mp4").exists()
