"""Conversion job tests (Specification §7-8): profile CRUD, production
replace, test-mode preserve, invalid-output safety, variant sweep,
skip-processed, and directory recursion excluding test artifacts.

Runs real ffmpeg/ffprobe against tiny synthetic videos generated by
make_video() (skipped automatically if ffmpeg/ffprobe aren't on PATH).
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest
from sqlalchemy import text

from app import conversion, conversion_profiles, conversion_settings, hardware_accel, performance_settings
from app.jobs import convert, service
from app.scan import scan_source

from .conftest import make_video

pytestmark = pytest.mark.skipif(
    shutil.which("ffmpeg") is None or shutil.which("ffprobe") is None,
    reason="ffmpeg/ffprobe not on PATH",
)


@pytest.fixture(autouse=True)
def _default_conversion_settings(engine):
    """Most tests in this module exercise replace *mechanics* (does the
    original get preserved/renamed correctly, etc.), not real-world
    compression ratios of trivial synthetic clips -- default the
    size-reduction gate to 0% (just don't come out bigger, the old
    behavior) so they aren't sensitive to how well a tiny testsrc clip
    happens to compress. Tests that exercise the gate itself set their own
    threshold explicitly."""
    conversion_settings.update_settings(engine, {"min_size_reduction_percent": 0})


def _make_profile(engine, **overrides) -> dict:
    data = {
        "name": "Test Profile",
        "video_codec": "h265",
        "container": "mp4",
        "crf": 30,
        "drop_audio": True,
        "max_dimension": None,
    }
    data.update(overrides)
    return conversion_profiles.create_profile(engine, data)


def _run_job(engine, scope_type: str, scope_ref: str | None, parameters: dict) -> dict:
    job = service.create_job(engine, "convert", scope_type, scope_ref, parameters)
    service.start_job(engine, job["id"])
    status, message = convert.run_convert_job(engine, job)
    service.finish_job(engine, job["id"], status, message)
    return service.get_job(engine, job["id"])


def _file_row(engine, relative_path: str):
    with engine.connect() as conn:
        return conn.execute(
            text("SELECT * FROM files WHERE relative_path = :rel"), {"rel": relative_path}
        ).fetchone()


# --- probe_media --------------------------------------------------------------


def test_probe_media_returns_none_instead_of_raising_on_null_stdout(tmp_path, monkeypatch):
    """Regression test: a 0 exit code with `stdout=None` (observed
    intermittently on Windows across many back-to-back ffprobe calls) used to
    raise an uncaught `TypeError` out of `json.loads(None)`, surfacing as a
    cryptic job-item failure message instead of the normal "not probeable"
    path."""
    fake_result = type("FakeResult", (), {"returncode": 0, "stdout": None})()
    monkeypatch.setattr(conversion.subprocess, "run", lambda *a, **k: fake_result)

    assert conversion.probe_media(tmp_path / "clip.mp4") is None


def test_probe_media_handles_non_ascii_path(tmp_path):
    """Regression test: `ffprobe`'s JSON output is UTF-8, but `subprocess.run`
    without an explicit `encoding` decodes with the OS console codepage (e.g.
    cp1252 on many Windows setups). For a path containing non-Latin-1
    characters (e.g. Cyrillic folder/file names), that mismatch used to raise
    a `UnicodeDecodeError` inside subprocess's stdout reader thread, silently
    truncating `result.stdout` and making a perfectly valid video look "not
    probeable"."""
    video_path = tmp_path / "Я умею любить" / "клип.mp4"
    make_video(video_path, duration=1.0, size="320x240")

    info = conversion.probe_media(video_path)
    assert info is not None
    assert info["has_video_stream"] is True
    assert info["duration"] is not None


# --- profile CRUD ------------------------------------------------------------


def test_profile_crud_and_default_exclusivity(engine, source):
    p1 = conversion_profiles.create_profile(engine, {"name": "A", "is_default": True})
    p2 = conversion_profiles.create_profile(engine, {"name": "B", "is_default": True})

    profiles = {p["id"]: p for p in conversion_profiles.list_profiles(engine)}
    assert profiles[p1["id"]]["is_default"] is False
    assert profiles[p2["id"]]["is_default"] is True

    updated = conversion_profiles.update_profile(engine, p1["id"], {**p1, "crf": 24})
    assert updated["crf"] == 24

    assert conversion_profiles.delete_profile(engine, p1["id"]) is True
    assert conversion_profiles.get_profile(engine, p1["id"]) is None


def test_profile_crud_round_trips_hardware_accel(engine, source):
    default_profile = conversion_profiles.create_profile(engine, {"name": "Default HW"})
    assert default_profile["hardware_accel"] == "off"

    qsv_profile = conversion_profiles.create_profile(engine, {"name": "QSV", "hardware_accel": "qsv"})
    assert qsv_profile["hardware_accel"] == "qsv"

    updated = conversion_profiles.update_profile(engine, qsv_profile["id"], {**qsv_profile, "hardware_accel": "vaapi"})
    assert updated["hardware_accel"] == "vaapi"


# --- production mode ----------------------------------------------------------


def test_production_mode_replaces_file(engine, source):
    make_video(source["root"] / "clips" / "movie.avi")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/movie.avi")

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "production"},
    )

    assert job["status"] == "completed"
    assert not (source["root"] / "clips" / "movie.avi").exists()
    converted_path = source["root"] / "clips" / "movie.mp4"
    assert converted_path.exists()

    info = conversion.probe_media(converted_path)
    assert info["video_codec_name"] == "hevc"

    row = _file_row(engine, "clips/movie.mp4")
    assert row is not None
    assert row.converted_at is not None
    assert row.last_conversion_profile_id == profile["id"]
    assert row.id == file_row.id  # same logical file, just renamed/re-encoded in place


def test_convert_job_logs_per_stage_progress_events(engine, source):
    """User request: same "what is it doing right now" visibility as
    preview jobs (see `test_preview.py`'s per-stage progress test) -- a
    `job_item_progress` event fires for probing, the ffmpeg encode, and
    output validation, between the file's `job_item_started`/
    `job_item_completed` events."""
    make_video(source["root"] / "clips" / "movie.avi")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/movie.avi")

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "production"},
    )
    assert job["status"] == "completed"

    with engine.connect() as conn:
        events = [
            (row.event_type, row.message)
            for row in conn.execute(
                text("SELECT event_type, message FROM app_events WHERE job_id = :id ORDER BY rowid"),
                {"id": job["id"]},
            ).all()
        ]
    event_types = [event_type for event_type, _ in events]
    progress_messages = [message for event_type, message in events if event_type == "job_item_progress"]

    # `.index()` alone would find the job-level "File: ..." progress event
    # logged before job_item_started (post-V1, user request to show the
    # source directory/file at the top of the log) -- look for the first
    # per-file progress event that comes after the item actually started.
    started_index = event_types.index("job_item_started")
    completed_index = event_types.index("job_item_completed")
    progress_index = next(
        i for i, event_type in enumerate(event_types) if event_type == "job_item_progress" and i > started_index
    )
    assert started_index < progress_index < completed_index
    assert any("Probed" in message for message in progress_messages)
    assert any("Encoding" in message or "Encoded" in message for message in progress_messages)
    assert any("Validated" in message for message in progress_messages)


def test_convert_job_logs_command_directory_and_size(engine, source):
    """User request: the job log should show the ffmpeg command line (to
    copy/paste and reproduce in a terminal), which file/directory is being
    converted, and the original vs. resulting resolution/file size, in
    human-readable units (a raw byte count "is very hard to read")."""
    make_video(source["root"] / "clips" / "movie.avi")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/movie.avi")

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "production"},
    )
    assert job["status"] == "completed"
    # scope_label (user request): the Jobs modal shouldn't have to fall back
    # to the raw file id for a file-scope job -- resolved live from the
    # file's current relative_path, so it reflects the post-conversion name.
    assert job["scope_label"] == "clips/movie.mp4"

    with engine.connect() as conn:
        messages = [
            row.message
            for row in conn.execute(
                text("SELECT message FROM app_events WHERE job_id = :id ORDER BY rowid"), {"id": job["id"]}
            ).all()
        ]

    assert any("File: clips/movie.avi" in message for message in messages)
    assert any("ffmpeg command:" in message and "-c:v" in message for message in messages)
    # Source resolution/size up front, resulting resolution/size after the
    # encode -- both in human-readable units (KB/MB/GB), not raw byte counts.
    assert any("Source: " in message and "x" in message and ("B" in message) for message in messages)
    source_line = next(message for message in messages if "Source: " in message)
    assert "bytes" not in source_line
    result_line = next(message for message in messages if "Result: " in message)
    assert "->" in result_line and "%" in result_line and "bytes" not in result_line

    # Live encode progress (user request): a successful encode always ends
    # by reporting 100% on its job_items row, even for a clip too short to
    # produce more than one `-progress` line.
    items = service.get_job_items(engine, job["id"])
    assert items[0]["progress_pct"] == 100.0


def test_run_ffmpeg_reports_progress(source):
    """User request: live within-file encode progress, parsed from ffmpeg's
    own `-progress` output, so the Jobs modal can show more than "file N of
    M" for a slow encode."""
    src = source["root"] / "clip.mp4"
    out = source["root"] / "out.mp4"
    make_video(src, duration=3)
    info = conversion.probe_media(src)
    args = conversion.build_ffmpeg_command(src, out, video_codec="h265", crf=30, drop_audio=True)

    progress_values: list[float] = []
    ok, err = conversion.run_ffmpeg(args, duration=info["duration"], on_progress=progress_values.append)

    assert ok, err
    assert progress_values
    assert all(0.0 <= value <= 100.0 for value in progress_values)
    assert progress_values[-1] == 100.0


def test_run_ffmpeg_should_stop_kills_the_process(source):
    """User request: cancelling a job should interrupt an in-flight ffmpeg
    encode right away instead of only being noticed once it finishes on its
    own (previously the only way out was `service.cancel_job`'s
    force-cancel path, which abandons the worker thread but leaves ffmpeg
    running to completion in the background)."""
    src = source["root"] / "clip.mp4"
    out = source["root"] / "out.mp4"
    make_video(src, duration=5)
    args = conversion.build_ffmpeg_command(src, out, video_codec="h265", crf=30, drop_audio=True)

    ok, err = conversion.run_ffmpeg(args, should_stop=lambda: True)

    assert ok is False
    assert err == "Cancelled."


def test_invalid_conversion_never_deletes_original(engine, source, monkeypatch):
    make_video(source["root"] / "clips" / "movie.mp4")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/movie.mp4")

    monkeypatch.setattr(conversion, "validate_converted_output", lambda *a, **k: (False, "forced invalid"))

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "production"},
    )

    assert job["status"] == "failed"
    assert (source["root"] / "clips" / "movie.mp4").exists()

    items = service.get_job_items(engine, job["id"])
    assert items[0]["status"] == "failed"
    assert "Validation failed" in items[0]["message"]

    row = _file_row(engine, "clips/movie.mp4")
    assert row.converted_at is None

    leftovers = list((source["root"] / "clips").glob(".movie.convert-*"))
    assert leftovers == []


def test_production_mode_skips_when_output_larger_than_source(engine, source, monkeypatch):
    """User report: a converted file that ends up bigger than the source is
    always a bad trade, regardless of the configured threshold. The
    encode/validation must still run (so the failure mode is observable),
    but the source is kept untouched and the item is marked "skipped", not
    "completed" or "failed"."""
    make_video(source["root"] / "clips" / "clip.mp4")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/clip.mp4")
    original_size = (source["root"] / "clips" / "clip.mp4").stat().st_size

    _bloat_ffmpeg_output(monkeypatch, extra_bytes=original_size + 1024)

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "production"},
    )

    assert job["status"] == "completed"
    assert (source["root"] / "clips" / "clip.mp4").exists()
    assert (source["root"] / "clips" / "clip.mp4").stat().st_size == original_size

    items = service.get_job_items(engine, job["id"])
    assert items[0]["status"] == "skipped"
    assert "only reduced size by" in items[0]["message"]

    row = _file_row(engine, "clips/clip.mp4")
    assert row.converted_at is None

    leftovers = list((source["root"] / "clips").glob(".clip.convert-*"))
    assert leftovers == []


def test_variant_sweep_keeps_variants_larger_than_source(engine, source, monkeypatch):
    """The size-reduction guard only applies to production/test-mode replace
    (user report). A tuning-sweep variant is a deliberate comparison output
    that never touches the source anyway, so it must not be rejected just
    for being bigger."""
    make_video(source["root"] / "clips" / "clip.mp4")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/clip.mp4")
    original_size = (source["root"] / "clips" / "clip.mp4").stat().st_size

    _bloat_ffmpeg_output(monkeypatch, extra_bytes=original_size + 1024)

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "test", "variants": [{"crf": 24}]},
    )

    assert job["status"] == "completed"
    items = service.get_job_items(engine, job["id"])
    assert items[0]["status"] == "completed"
    assert (source["root"] / "clips" / "clip.variant-crf24.mp4").stat().st_size > original_size


def _bloat_ffmpeg_output(monkeypatch, *, extra_bytes: int) -> None:
    """Runs real ffmpeg, then pads its output past `source_size` so any
    size-reduction threshold sees a negative reduction deterministically,
    without depending on how well a tiny synthetic clip actually compresses."""
    real_run_ffmpeg = conversion.run_ffmpeg

    def bloated_run_ffmpeg(args, timeout=3600, **kwargs):
        ok, err = real_run_ffmpeg(args, timeout=timeout, **kwargs)
        if ok:
            with open(Path(args[-1]), "ab") as f:
                f.write(b"0" * extra_bytes)
        return ok, err

    monkeypatch.setattr(conversion, "run_ffmpeg", bloated_run_ffmpeg)


def test_convert_job_uses_configured_ffmpeg_timeout(engine, source, monkeypatch):
    """User report: a slow encode hit the previously-hardcoded 3600s limit in
    `conversion.run_ffmpeg` and was killed outright. The configured
    `ffmpeg_timeout_seconds` (`app/conversion_settings.py`) must reach the
    actual `run_ffmpeg` call made for each file's encode."""
    make_video(source["root"] / "clips" / "clip.mp4", size="480x360", duration=1.0)
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/clip.mp4")

    conversion_settings.update_settings(engine, {"ffmpeg_timeout_seconds": 90})

    real_run_ffmpeg = conversion.run_ffmpeg
    seen_timeouts: list[int] = []

    def spying_run_ffmpeg(args, timeout=3600, **kwargs):
        seen_timeouts.append(timeout)
        return real_run_ffmpeg(args, timeout=timeout, **kwargs)

    monkeypatch.setattr(conversion, "run_ffmpeg", spying_run_ffmpeg)

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "production"},
    )

    assert job["status"] == "completed"
    assert seen_timeouts == [90]


def test_production_mode_skips_when_reduction_below_configured_threshold(engine, source):
    """User report: a small real reduction isn't good enough on its own --
    it must clear the configured minimum percentage, or the original is
    kept. A trivial synthetic clip's real h265 encode shrinks it only
    modestly (well under the 20% default), so no monkeypatching is needed
    to exercise this against a genuinely smaller-but-insufficient output."""
    make_video(source["root"] / "clips" / "clip.mp4", size="480x360", duration=1.0)
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/clip.mp4")
    original_size = (source["root"] / "clips" / "clip.mp4").stat().st_size

    conversion_settings.update_settings(engine, {"min_size_reduction_percent": 20})

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "production"},
    )

    assert job["status"] == "completed"
    assert (source["root"] / "clips" / "clip.mp4").stat().st_size == original_size

    items = service.get_job_items(engine, job["id"])
    assert items[0]["status"] == "skipped"
    assert "needs at least 20%" in items[0]["message"]

    row = _file_row(engine, "clips/clip.mp4")
    assert row.converted_at is None


def test_production_mode_replaces_when_reduction_meets_configured_threshold(engine, source):
    """Same real (modest) encode as the test above, but with a threshold low
    enough for it to clear -- the replace goes through normally."""
    make_video(source["root"] / "clips" / "clip.mp4", size="480x360", duration=1.0)
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/clip.mp4")
    original_size = (source["root"] / "clips" / "clip.mp4").stat().st_size

    conversion_settings.update_settings(engine, {"min_size_reduction_percent": 5})

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "production"},
    )

    assert job["status"] == "completed"
    items = service.get_job_items(engine, job["id"])
    assert items[0]["status"] == "completed"
    assert (source["root"] / "clips" / "clip.mp4").stat().st_size < original_size

    row = _file_row(engine, "clips/clip.mp4")
    assert row.converted_at is not None


# --- hardware-accelerated encoding fallback (app/hardware_accel.py) ------------


def test_convert_job_falls_back_to_software_when_hw_unavailable(engine, source, monkeypatch):
    """A profile requesting `hardware_accel="qsv"` on a host where the
    startup probe found QSV unusable must still convert successfully, via
    the software encoder, with the reason logged rather than the job simply
    failing or silently ignoring the requested setting."""
    make_video(source["root"] / "clips" / "clip.mp4", size="480x360", duration=1.0)
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine, hardware_accel="qsv")
    file_row = _file_row(engine, "clips/clip.mp4")

    monkeypatch.setattr(
        hardware_accel, "check_hardware_accel",
        lambda **kwargs: hardware_accel.HardwareAccelStatus(qsv=False, vaapi=False),
    )

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "production"},
    )

    assert job["status"] == "completed"
    converted_path = source["root"] / "clips" / "clip.mp4"
    assert converted_path.exists()
    assert conversion.probe_media(converted_path)["video_codec_name"] == "hevc"

    with engine.connect() as conn:
        messages = [
            row.message
            for row in conn.execute(
                text("SELECT message FROM app_events WHERE job_id = :id ORDER BY rowid"), {"id": job["id"]}
            ).all()
        ]
    assert any("qsv hardware encoding unavailable on this host" in message for message in messages)


def test_convert_job_retries_with_software_after_hw_runtime_failure(engine, source, monkeypatch):
    """The upfront probe may say QSV is available, but the actual encode can
    still fail at runtime -- the job must retry once with the software
    encoder rather than failing the file outright, and the log must show
    both the original failure and the retry, never hiding one for the
    other."""
    make_video(source["root"] / "clips" / "clip.mp4", size="480x360", duration=1.0)
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine, hardware_accel="qsv")
    file_row = _file_row(engine, "clips/clip.mp4")

    monkeypatch.setattr(
        hardware_accel, "check_hardware_accel",
        lambda **kwargs: hardware_accel.HardwareAccelStatus(qsv=True, vaapi=False),
    )

    real_run_ffmpeg = conversion.run_ffmpeg
    calls = {"n": 0}

    def flaky_run_ffmpeg(args, timeout=3600, **kwargs):
        calls["n"] += 1
        if calls["n"] == 1:
            return False, "simulated qsv failure"
        return real_run_ffmpeg(args, timeout=timeout, **kwargs)

    monkeypatch.setattr(conversion, "run_ffmpeg", flaky_run_ffmpeg)

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "production"},
    )

    assert job["status"] == "completed"
    assert calls["n"] == 2
    assert (source["root"] / "clips" / "clip.mp4").exists()

    with engine.connect() as conn:
        messages = [
            row.message
            for row in conn.execute(
                text("SELECT message FROM app_events WHERE job_id = :id ORDER BY rowid"), {"id": job["id"]}
            ).all()
        ]
    assert any("simulated qsv failure" in message for message in messages)
    assert any("retrying this file with the software encoder" in message for message in messages)


def test_convert_job_no_hw_mapping_falls_back_silently_logged(engine, source):
    """A `hardware_accel` value with no registered ffmpeg encoder mapping for
    the profile's codec (e.g. a value with no `(codec, backend)` entry in
    `conversion._HW_CODEC_INFO`) must fall back to software before ever
    consulting the availability probe, and say why in the job log."""
    make_video(source["root"] / "clips" / "clip.mp4", size="480x360", duration=1.0)
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine, hardware_accel="nvenc")
    file_row = _file_row(engine, "clips/clip.mp4")

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "production"},
    )

    assert job["status"] == "completed"
    assert (source["root"] / "clips" / "clip.mp4").exists()

    with engine.connect() as conn:
        messages = [
            row.message
            for row in conn.execute(
                text("SELECT message FROM app_events WHERE job_id = :id ORDER BY rowid"), {"id": job["id"]}
            ).all()
        ]
    assert any("No nvenc encoder for codec h265; using software encoder." in message for message in messages)


# --- test mode -----------------------------------------------------------------


def test_test_mode_preserves_original_same_extension(engine, source):
    # Bigger than the module default: a trivially tiny clip's re-encode can
    # come out larger than the source from container/codec overhead alone,
    # which the larger-than-source guard would (correctly) skip instead of
    # replacing -- see test_production_mode_skips_when_output_larger_than_source.
    make_video(source["root"] / "clips" / "clip.mp4", size="480x360", duration=1.0)
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/clip.mp4")

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "test"},
    )

    assert job["status"] == "completed"
    assert (source["root"] / "clips" / "clip.original.mp4").exists()
    assert (source["root"] / "clips" / "clip.mp4").exists()

    original_row = _file_row(engine, "clips/clip.original.mp4")
    converted_row = _file_row(engine, "clips/clip.mp4")
    assert original_row.id == file_row.id
    assert original_row.converted_at is None
    assert converted_row.id != original_row.id
    assert converted_row.converted_at is not None


def test_test_mode_preserves_original_different_extension(engine, source):
    make_video(source["root"] / "clips" / "clip.mov", size="480x360", duration=1.0)
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/clip.mov")

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "test"},
    )

    assert job["status"] == "completed"
    assert (source["root"] / "clips" / "clip.original.mov").exists()
    assert (source["root"] / "clips" / "clip.mp4").exists()


def test_invalid_test_mode_conversion_never_touches_original(engine, source, monkeypatch):
    make_video(source["root"] / "clips" / "clip.mp4")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/clip.mp4")

    monkeypatch.setattr(conversion, "validate_converted_output", lambda *a, **k: (False, "forced invalid"))

    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "test"},
    )

    assert job["status"] == "failed"
    assert (source["root"] / "clips" / "clip.mp4").exists()
    assert not (source["root"] / "clips" / "clip.original.mp4").exists()


# --- variant comparison --------------------------------------------------------


def test_variant_sweep_never_touches_source(engine, source):
    make_video(source["root"] / "clips" / "clip.mp4")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/clip.mp4")
    original_size = (source["root"] / "clips" / "clip.mp4").stat().st_size

    variants = [{"crf": 24}, {"max_dimension": 100, "crf": 30}]
    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "test", "variants": variants},
    )

    assert job["status"] == "completed"
    assert (source["root"] / "clips" / "clip.mp4").exists()
    assert (source["root"] / "clips" / "clip.mp4").stat().st_size == original_size

    variant_files = sorted(p.name for p in (source["root"] / "clips").glob("clip.variant-*.mp4"))
    assert variant_files == ["clip.variant-crf24.mp4", "clip.variant-d100-crf30.mp4"]

    items = service.get_job_items(engine, job["id"])
    assert len(items) == 2
    assert all(item["status"] == "completed" for item in items)

    row = _file_row(engine, "clips/clip.mp4")
    assert row.converted_at is None


def test_variant_sweep_tags_each_variant_with_its_parameters(engine, source):
    """Every tuning-produced file carries its effective encode parameters as
    ordinary vocabulary tags (user request): codec and CRF always, the
    dimension cap when one applied -- provider `tuning`, so the UI can label
    them, and removable like any other tag. Re-running the same sweep must
    not duplicate the assignments."""
    make_video(source["root"] / "clips" / "clip.mp4")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)  # video_codec h265
    file_row = _file_row(engine, "clips/clip.mp4")

    params = {
        "file_id": file_row.id, "profile_id": profile["id"], "mode": "test",
        "variants": [{"crf": 24}, {"max_dimension": 100, "crf": 30}],
    }
    assert _run_job(engine, "file", file_row.id, params)["status"] == "completed"
    # Second identical sweep: overwrites the files, must not double the tags.
    assert _run_job(engine, "file", file_row.id, params)["status"] == "completed"

    def variant_tags(rel: str) -> list[tuple[str, str, int]]:
        with engine.connect() as conn:
            rows = conn.execute(
                text(
                    """
                    SELECT tc.display_name, ft.provider_name, ft.score
                    FROM file_tags ft
                    JOIN tag_catalog tc ON tc.id = ft.tag_id
                    JOIN files f ON f.id = ft.file_id
                    WHERE f.relative_path = :rel
                    ORDER BY tc.display_name
                    """
                ),
                {"rel": rel},
            ).all()
        return [(row.display_name, row.provider_name, row.score) for row in rows]

    assert variant_tags("clips/clip.variant-crf24.mp4") == [
        ("CRF 24", "tuning", 100),
        ("H265", "tuning", 100),
    ]
    assert variant_tags("clips/clip.variant-d100-crf30.mp4") == [
        ("100px", "tuning", 100),
        ("CRF 30", "tuning", 100),
        ("H265", "tuning", 100),
    ]

    # The source file itself is untouched: no tags, still not "tagged".
    assert variant_tags("clips/clip.mp4") == []
    assert _file_row(engine, "clips/clip.variant-crf24.mp4").tagged_at is None


def test_repeated_variant_combination_across_sweeps_does_not_fail(engine, source):
    """Regression: two separate tuning sweeps for the same source file (e.g.
    a dimension sweep, then later a CRF sweep) can reproduce an identical
    `(dimension, crf)` combination the other sweep already wrote to disk
    under the same `<stem>.variant-<params>.<ext>` name. `_create_variant`
    must overwrite that file's `files` row (UPDATE) instead of blindly
    INSERTing a second one for the same `(source_id, relative_path)`, which
    violates that pair's UNIQUE constraint."""
    make_video(source["root"] / "clips" / "clip.mp4")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/clip.mp4")

    first = _run_job(
        engine, "file", file_row.id,
        {
            "file_id": file_row.id, "profile_id": profile["id"], "mode": "test",
            "variants": [{"max_dimension": 100, "crf": 26}, {"max_dimension": 200, "crf": 26}],
        },
    )
    assert first["status"] == "completed"

    # A later, separate sweep reproduces one of the same combinations.
    second = _run_job(
        engine, "file", file_row.id,
        {
            "file_id": file_row.id, "profile_id": profile["id"], "mode": "test",
            "variants": [{"max_dimension": 100, "crf": 26}, {"max_dimension": 100, "crf": 30}],
        },
    )
    assert second["status"] == "completed"
    items = service.get_job_items(engine, second["id"])
    assert all(item["status"] == "completed" for item in items)

    with engine.connect() as conn:
        count = conn.execute(
            text(
                "SELECT COUNT(*) FROM files WHERE source_id = :sid AND relative_path = :rel"
            ),
            {"sid": file_row.source_id, "rel": "clips/clip.variant-d100-crf26.mp4"},
        ).scalar()
    assert count == 1


# --- skip-processed and directory recursion ------------------------------------


def test_directory_scope_skip_processed(engine, source):
    make_video(source["root"] / "clips" / "a.mp4", size="480x360", duration=1.0)
    make_video(source["root"] / "clips" / "b.mp4", size="480x360", duration=1.0)
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)

    a_row = _file_row(engine, "clips/a.mp4")
    with engine.begin() as conn:
        conn.execute(
            text("UPDATE files SET converted_at = :now WHERE id = :id"),
            {"now": "2020-01-01T00:00:00+00:00", "id": a_row.id},
        )

    job = _run_job(
        engine, "directory", "clips",
        {"path": "clips", "profile_id": profile["id"], "mode": "production", "skip_processed": True},
    )

    assert job["status"] == "completed"
    items = service.get_job_items(engine, job["id"])
    statuses = sorted(item["status"] for item in items)
    assert statuses == ["completed", "skipped"]


def test_directory_recursive_conversion_excludes_test_artifacts(engine, source):
    make_video(source["root"] / "top.mp4")
    make_video(source["root"] / "sub" / "nested.mp4")
    (source["root"] / "sub" / "already.original.mp4").write_bytes(b"0")
    (source["root"] / "sub" / "already.variant-crf28.mp4").write_bytes(b"0")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)

    job = _run_job(
        engine, "source", None,
        {"path": "", "profile_id": profile["id"], "mode": "production", "skip_processed": True},
    )

    assert job["status"] == "completed"
    items = service.get_job_items(engine, job["id"])
    assert len(items) == 2  # top.mp4 + sub/nested.mp4 only; the two artifacts are excluded entirely

    assert (source["root"] / "top.mp4").exists()
    assert (source["root"] / "sub" / "nested.mp4").exists()


def test_directory_test_mode_recursive(engine, source):
    make_video(source["root"] / "top.mp4", size="480x360", duration=1.0)
    make_video(source["root"] / "sub" / "nested.mp4", size="480x360", duration=1.0)
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)

    job = _run_job(
        engine, "source", None,
        {"path": "", "profile_id": profile["id"], "mode": "test", "skip_processed": True},
    )

    assert job["status"] == "completed"
    assert (source["root"] / "top.original.mp4").exists()
    assert (source["root"] / "top.mp4").exists()
    assert (source["root"] / "sub" / "nested.original.mp4").exists()
    assert (source["root"] / "sub" / "nested.mp4").exists()


# --- parallel processing (post-V1, user request) --------------------------


def test_directory_scope_converts_all_files_across_multiple_batches(engine, source):
    """`parallel_workers=2` against 5 candidate files forces the
    directory-scope loop through three flushed batches (2 + 2 + 1) instead
    of one -- every file must still end up converted and counted exactly
    once regardless of the batch boundaries."""
    performance_settings.update_settings(engine, {"parallel_workers": 2})
    for i in range(5):
        make_video(source["root"] / "clips" / f"clip_{i}.mp4", size="480x360", duration=1.0)
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)

    job = _run_job(
        engine, "source", None,
        {"path": "", "profile_id": profile["id"], "mode": "production", "skip_processed": True},
    )

    assert job["status"] == "completed"
    assert "Converted 5 of 5 file(s)" in job["summary_message"]
    items = service.get_job_items(engine, job["id"])
    assert len(items) == 5
    assert all(item["status"] == "completed" for item in items)
    for i in range(5):
        assert (source["root"] / "clips" / f"clip_{i}.mp4").exists()


def test_variant_sweep_produces_all_variants_across_multiple_batches(engine, source):
    """Same batching concern as above, applied to a single file's variant
    sweep (the "one file, many threads" case)."""
    performance_settings.update_settings(engine, {"parallel_workers": 2})
    make_video(source["root"] / "clips" / "clip.mp4")
    scan_source(engine, source["id"], source["root"])
    profile = _make_profile(engine)
    file_row = _file_row(engine, "clips/clip.mp4")

    variants = [{"crf": 20}, {"crf": 24}, {"crf": 28}, {"crf": 32}, {"crf": 36}]
    job = _run_job(
        engine, "file", file_row.id,
        {"file_id": file_row.id, "profile_id": profile["id"], "mode": "test", "variants": variants},
    )

    assert job["status"] == "completed"
    variant_files = sorted(p.name for p in (source["root"] / "clips").glob("clip.variant-*.mp4"))
    assert len(variant_files) == 5

    items = service.get_job_items(engine, job["id"])
    assert len(items) == 5
    assert all(item["status"] == "completed" for item in items)
