"""Generates a standalone PowerShell script that reproduces a batch
directory conversion outside the app (user request): the user can copy it
and run it on any Windows machine with access to the same directory (e.g.
over SMB), without the backend or job queue involved at all.

Reuses the real conversion machinery -- `app.conversion.resolve_encoder()`/
`has_hw_mapping()` and `app.jobs.convert._effective_params()` -- so the
script's ffmpeg invocation is built exactly the same way a real `convert`
job would build it, just rendered as text instead of executed.
"""

from __future__ import annotations

from sqlalchemy import text

from app import conversion
from app.jobs.convert import _effective_params
from app.media import is_test_artifact


def enumerate_directory_files(engine, source_id: str, relative_path: str) -> list[str]:
    """Relative paths of every video file a `convert-directory` job would
    process for this same directory scope -- identical query/filter to
    `app/jobs/convert.py::_run_directory_scope()`, so the generated script's
    file list always matches what a real conversion job would touch."""
    clauses = ["source_id = :sid", "is_video_supported = 1"]
    params: dict = {"sid": source_id}
    if relative_path:
        clauses.append("(relative_path = :rel OR relative_path LIKE :prefix)")
        params["rel"] = relative_path
        params["prefix"] = f"{relative_path}/%"

    with engine.connect() as conn:
        rows = conn.execute(
            text(
                f"SELECT relative_path, file_name FROM files WHERE {' AND '.join(clauses)} "
                "ORDER BY relative_path"
            ),
            params,
        ).all()

    return [row.relative_path for row in rows if not is_test_artifact(row.file_name)]


def _ps_string(value: str) -> str:
    """Single-quoted PowerShell string literal; the only escaping a
    single-quoted PS string needs is doubling embedded single quotes."""
    return "'" + value.replace("'", "''") + "'"


def generate_powershell_script(
    *, profile: dict, overrides: dict | None, root_hint: str, relative_paths: list[str]
) -> tuple[str, str]:
    """Returns `(script_text, container)`."""
    params = _effective_params(profile, overrides)
    hardware_accel = params["hardware_accel"]
    encoder = conversion.resolve_encoder(params["video_codec"], hardware_accel)
    using_hw_encoder = hardware_accel != "off" and conversion.has_hw_mapping(params["video_codec"], hardware_accel)
    container = params["container"]
    extra_args = params.get("extra_encoder_args") or []

    files_block = "\n".join(f"  {_ps_string(rel_path)}" for rel_path in relative_paths)
    extra_args_block = ", ".join(_ps_string(arg) for arg in extra_args)

    script = f"""<#
Generated by Video Archive -- reproduces a batch directory conversion
standalone. Run from a machine with filesystem access to $Root (a local path
or a \\\\host\\share UNC path). Requires ffmpeg and ffprobe on PATH.

Safe-replace guarantee (matches the app's production-mode conversion):
encodes to a temporary file next to the source first, only replaces the
source once ffmpeg exits successfully and the temp file is non-empty; on
failure the temp file is discarded and the source is left untouched.
#>
param(
    [string]$Root = {_ps_string(root_hint)}
)

$ErrorActionPreference = 'Continue'
$Encoder = {_ps_string(encoder)}
$Crf = {params["crf"]}
$Preset = {_ps_string(params.get("preset") or "medium")}
$UsingHardwareEncoder = ${"true" if using_hw_encoder else "false"}
$MaxDimension = {params.get("max_dimension") or 0}
$DropAudio = ${"true" if params["drop_audio"] else "false"}
$Container = {_ps_string(container)}
$ExtraEncoderArgs = @({extra_args_block})

function Convert-OneFile([string]$RelativePath) {{
    $InputPath = Join-Path $Root $RelativePath
    if (-not (Test-Path -LiteralPath $InputPath)) {{
        Write-Warning "Missing, skipped: $RelativePath"
        return
    }}

    $ScaleFilter = $null
    if ($MaxDimension -gt 0) {{
        $probeJson = & ffprobe -v error -print_format json -show_streams -select_streams v:0 -- $InputPath
        $probe = $probeJson | ConvertFrom-Json
        $videoStream = $probe.streams | Select-Object -First 1
        if ($videoStream -and ([Math]::Max($videoStream.width, $videoStream.height) -gt $MaxDimension)) {{
            $ScaleFilter = "scale='if(gt(iw,ih),min(iw,$MaxDimension),-2)':'if(gt(iw,ih),-2,min(ih,$MaxDimension))'"
        }}
    }}

    $Stem = [System.IO.Path]::GetFileNameWithoutExtension($InputPath)
    $Dir = Split-Path -LiteralPath $InputPath
    $TempName = ".$Stem.convert-$([guid]::NewGuid().ToString('N').Substring(0, 8)).$Container"
    $TempPath = Join-Path $Dir $TempName

    $FfmpegArgs = @('-y', '-i', $InputPath, '-c:v', $Encoder, '-crf', "$Crf")
    if (-not $UsingHardwareEncoder) {{
        $FfmpegArgs += @('-preset', $Preset)
    }}
    if ($ScaleFilter) {{
        $FfmpegArgs += @('-vf', $ScaleFilter)
    }}
    if ($DropAudio) {{
        $FfmpegArgs += '-an'
    }} else {{
        $FfmpegArgs += @('-c:a', 'copy')
    }}
    $FfmpegArgs += $ExtraEncoderArgs
    if ($Container -eq 'mp4') {{
        $FfmpegArgs += @('-movflags', '+faststart')
    }}
    $FfmpegArgs += $TempPath

    Write-Host "Converting: $RelativePath"
    & ffmpeg @FfmpegArgs
    $ExitCode = $LASTEXITCODE

    if ($ExitCode -ne 0 -or -not (Test-Path -LiteralPath $TempPath) -or (Get-Item -LiteralPath $TempPath).Length -eq 0) {{
        Write-Warning "Failed (ffmpeg exit $ExitCode), original left untouched: $RelativePath"
        if (Test-Path -LiteralPath $TempPath) {{
            Remove-Item -LiteralPath $TempPath -Force
        }}
        return
    }}

    $FinalPath = Join-Path $Dir "$Stem.$Container"
    if ($FinalPath -eq $InputPath) {{
        Move-Item -LiteralPath $TempPath -Destination $InputPath -Force
    }} else {{
        Move-Item -LiteralPath $TempPath -Destination $FinalPath -Force
        Remove-Item -LiteralPath $InputPath -Force
    }}
    Write-Host "Converted: $RelativePath"
}}

$Files = @(
{files_block}
)

foreach ($RelativePath in $Files) {{
    Convert-OneFile $RelativePath
}}
"""
    return script, container
